# CMake generated Testfile for 
# Source directory: /home/wma/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/AudioPlayer/test
# Build directory: /home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(AudioPlayerTest.testCreateWithNullPointers "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testCreateWithNullPointers")
add_test(AudioPlayerTest.testTransitionFromIdleToPlaying "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testTransitionFromIdleToPlaying")
add_test(AudioPlayerTest.testTransitionFromPlayingToStopped "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testTransitionFromPlayingToStopped")
add_test(AudioPlayerTest.testTransitionFromPlayingToStoppedWithClear "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testTransitionFromPlayingToStoppedWithClear")
add_test(AudioPlayerTest.testTransitionFromStoppedToPlaying "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testTransitionFromStoppedToPlaying")
add_test(AudioPlayerTest.testTransitionFromPlayingToPaused "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testTransitionFromPlayingToPaused")
add_test(AudioPlayerTest.testTransitionFromPausedToStopped "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testTransitionFromPausedToStopped")
add_test(AudioPlayerTest.testResumeAfterPaused "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testResumeAfterPaused")
add_test(AudioPlayerTest.testCallingProvideStateWhenIdle "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testCallingProvideStateWhenIdle")
add_test(AudioPlayerTest.testOnPlaybackError "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testOnPlaybackError")
add_test(AudioPlayerTest.testOnPlaybackPaused "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testOnPlaybackPaused")
add_test(AudioPlayerTest.testOnPlaybackResumed "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testOnPlaybackResumed")
add_test(AudioPlayerTest.testOnPlaybackFinished "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testOnPlaybackFinished")
add_test(AudioPlayerTest.testOnBufferUnderrun "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testOnBufferUnderrun")
add_test(AudioPlayerTest.testOnBufferRefilled "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testOnBufferRefilled")
add_test(AudioPlayerTest.testOnTags "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testOnTags")
add_test(AudioPlayerTest.testCancelDirective "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testCancelDirective")
add_test(AudioPlayerTest.testFocusChangeToNoneInIdleState "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testFocusChangeToNoneInIdleState")
add_test(AudioPlayerTest.testFocusChangeFromForegroundToBackgroundInIdleState "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testFocusChangeFromForegroundToBackgroundInIdleState")
add_test(AudioPlayerTest.testFocusChangeFromNoneToBackgroundInIdleState "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testFocusChangeFromNoneToBackgroundInIdleState")
add_test(AudioPlayerTest.testFocusChangesInPlayingState "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testFocusChangesInPlayingState")
add_test(AudioPlayerTest.testFocusChangesInStoppedState "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testFocusChangesInStoppedState")
add_test(AudioPlayerTest.testFocusChangesInPausedState "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testFocusChangesInPausedState")
add_test(AudioPlayerTest.testFocusChangesInBufferUnderrunState "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testFocusChangesInBufferUnderrunState")
add_test(AudioPlayerTest.testFocusChangeToBackgroundBeforeOnPlaybackStarted "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testFocusChangeToBackgroundBeforeOnPlaybackStarted")
add_test(AudioPlayerTest.testPlayAfterOnPlaybackError "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testPlayAfterOnPlaybackError")
add_test(AudioPlayerTest.testPlaybackStartedSwitchesHandler "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testPlaybackStartedSwitchesHandler")
add_test(AudioPlayerTest.testProgressReportDelayElapsed "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testProgressReportDelayElapsed")
add_test(AudioPlayerTest.testProgressReportDelayElapsedDelayLessThanOffset "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testProgressReportDelayElapsedDelayLessThanOffset")
add_test(AudioPlayerTest.testProgressReportIntervalElapsed "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testProgressReportIntervalElapsed")
add_test(AudioPlayerTest.testProgressReportIntervalElapsedIntervalLessThanOffset "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/AudioPlayerTest" "--gtest_filter=AudioPlayerTest.testProgressReportIntervalElapsedIntervalLessThanOffset")
add_test(IntervalCalculatorTest.intervalGreaterThanOffset "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/IntervalCalculatorTest" "--gtest_filter=IntervalCalculatorTest.intervalGreaterThanOffset")
add_test(IntervalCalculatorTest.intervalEqualToOffset "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/IntervalCalculatorTest" "--gtest_filter=IntervalCalculatorTest.intervalEqualToOffset")
add_test(IntervalCalculatorTest.intervalLessThanOffset "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/IntervalCalculatorTest" "--gtest_filter=IntervalCalculatorTest.intervalLessThanOffset")
add_test(IntervalCalculatorTest.intervalLessThanOffsetByMultipleTimes "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/IntervalCalculatorTest" "--gtest_filter=IntervalCalculatorTest.intervalLessThanOffsetByMultipleTimes")
add_test(IntervalCalculatorTest.intervalNegative "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/IntervalCalculatorTest" "--gtest_filter=IntervalCalculatorTest.intervalNegative")
add_test(IntervalCalculatorTest.offsetNegative "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/IntervalCalculatorTest" "--gtest_filter=IntervalCalculatorTest.offsetNegative")
add_test(IntervalCalculatorTest.intervalAndoffsetNegative "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/IntervalCalculatorTest" "--gtest_filter=IntervalCalculatorTest.intervalAndoffsetNegative")
add_test(IntervalCalculatorTest.intervalZero "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/IntervalCalculatorTest" "--gtest_filter=IntervalCalculatorTest.intervalZero")
add_test(IntervalCalculatorTest.offsetZero "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/IntervalCalculatorTest" "--gtest_filter=IntervalCalculatorTest.offsetZero")
add_test(IntervalCalculatorTest.nullOutputParameter "/home/wma/sdk-folder/sdk-build/CapabilityAgents/AudioPlayer/test/IntervalCalculatorTest" "--gtest_filter=IntervalCalculatorTest.nullOutputParameter")
