# CMake generated Testfile for 
# Source directory: /home/wma/sdk-folder/sdk-source/avs-device-sdk/ACL/test
# Build directory: /home/wma/sdk-folder/sdk-build/ACL/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(AVSConnectionManagerTest.createTest "/home/wma/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.createTest")
add_test(AVSConnectionManagerTest.createWithNullMessageRouterAndObservers "/home/wma/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.createWithNullMessageRouterAndObservers")
add_test(AVSConnectionManagerTest.addConnectionStatusObserverNull "/home/wma/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.addConnectionStatusObserverNull")
add_test(AVSConnectionManagerTest.addConnectionStatusObserverValid "/home/wma/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.addConnectionStatusObserverValid")
add_test(AVSConnectionManagerTest.removeConnectionStatusObserverNull "/home/wma/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.removeConnectionStatusObserverNull")
add_test(AVSConnectionManagerTest.addMessageObserverNull "/home/wma/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.addMessageObserverNull")
add_test(AVSConnectionManagerTest.removeMessageObserverNull "/home/wma/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.removeMessageObserverNull")
add_test(AVSConnectionManagerTest.enableAndDisableFunction "/home/wma/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.enableAndDisableFunction")
add_test(AVSConnectionManagerTest.sendMessageRequestTest "/home/wma/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.sendMessageRequestTest")
add_test(AVSConnectionManagerTest.setAVSEndpointTest "/home/wma/sdk-folder/sdk-build/ACL/test/AVSConnectionManagerTest" "--gtest_filter=AVSConnectionManagerTest.setAVSEndpointTest")
add_test(HTTP2StreamTest.testExceptionReceivedSingleWrite "/home/wma/sdk-folder/sdk-build/ACL/test/HTTP2StreamTest" "--gtest_filter=HTTP2StreamTest.testExceptionReceivedSingleWrite")
add_test(HTTP2StreamTest.testExceptionReceivedMultiWrite "/home/wma/sdk-folder/sdk-build/ACL/test/HTTP2StreamTest" "--gtest_filter=HTTP2StreamTest.testExceptionReceivedMultiWrite")
add_test(HTTP2StreamTest.testHeaderCallback "/home/wma/sdk-folder/sdk-build/ACL/test/HTTP2StreamTest" "--gtest_filter=HTTP2StreamTest.testHeaderCallback")
add_test(HTTP2StreamTest.testReadCallBack "/home/wma/sdk-folder/sdk-build/ACL/test/HTTP2StreamTest" "--gtest_filter=HTTP2StreamTest.testReadCallBack")
add_test(MimeParserFuzzTest.testRandomFeedAndReadSizesOfRandomData "/home/wma/sdk-folder/sdk-build/ACL/test/MimeParserFuzzTest" "--gtest_filter=MimeParserFuzzTest.testRandomFeedAndReadSizesOfRandomData")
add_test(MimeParserTest.testDirectiveReceivedSingleWrite "/home/wma/sdk-folder/sdk-build/ACL/test/MimeParserTest" "--gtest_filter=MimeParserTest.testDirectiveReceivedSingleWrite")
add_test(MimeParserTest.testDirectiveReceivedMultiWrite "/home/wma/sdk-folder/sdk-build/ACL/test/MimeParserTest" "--gtest_filter=MimeParserTest.testDirectiveReceivedMultiWrite")
add_test(MimeParserTest.testAttachmentReceivedSingleWrite "/home/wma/sdk-folder/sdk-build/ACL/test/MimeParserTest" "--gtest_filter=MimeParserTest.testAttachmentReceivedSingleWrite")
add_test(MimeParserTest.testAttachmentReceivedMultiWrite "/home/wma/sdk-folder/sdk-build/ACL/test/MimeParserTest" "--gtest_filter=MimeParserTest.testAttachmentReceivedMultiWrite")
add_test(MimeParserTest.testDirectiveAndAttachmentReceivedSingleWrite "/home/wma/sdk-folder/sdk-build/ACL/test/MimeParserTest" "--gtest_filter=MimeParserTest.testDirectiveAndAttachmentReceivedSingleWrite")
add_test(MimeParserTest.testDirectiveAndAttachmentReceivedMultiWrite "/home/wma/sdk-folder/sdk-build/ACL/test/MimeParserTest" "--gtest_filter=MimeParserTest.testDirectiveAndAttachmentReceivedMultiWrite")
add_test(MimeParserTest.testDuplicateBounaries "/home/wma/sdk-folder/sdk-build/ACL/test/MimeParserTest" "--gtest_filter=MimeParserTest.testDuplicateBounaries")
add_test(MessageRouterTest.getConnectionStatusReturnsDisconnectedBeforeConnect "/home/wma/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.getConnectionStatusReturnsDisconnectedBeforeConnect")
add_test(MessageRouterTest.getConnectionStatusReturnsPendingAfterConnectingStarts "/home/wma/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.getConnectionStatusReturnsPendingAfterConnectingStarts")
add_test(MessageRouterTest.getConnectionStatusReturnsConnectedAfterConnectionEstablished "/home/wma/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.getConnectionStatusReturnsConnectedAfterConnectionEstablished")
add_test(MessageRouterTest.getConnectionStatusReturnsConnectedAfterDisconnected "/home/wma/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.getConnectionStatusReturnsConnectedAfterDisconnected")
add_test(MessageRouterTest.ensureTheMessageRouterObserverIsInformedOfConnectionPendingAfterConnect "/home/wma/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.ensureTheMessageRouterObserverIsInformedOfConnectionPendingAfterConnect")
add_test(MessageRouterTest.ensureTheMessageRouterObserverIsInformedOfNewConnection "/home/wma/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.ensureTheMessageRouterObserverIsInformedOfNewConnection")
add_test(MessageRouterTest.ensureTheMessageRouterObserverIsInformedOfTransportDisconnection "/home/wma/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.ensureTheMessageRouterObserverIsInformedOfTransportDisconnection")
add_test(MessageRouterTest.ensureTheMessageRouterObserverIsInformedOfRouterDisconnection "/home/wma/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.ensureTheMessageRouterObserverIsInformedOfRouterDisconnection")
add_test(MessageRouterTest.sendIsSuccessfulWhenConnected "/home/wma/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.sendIsSuccessfulWhenConnected")
add_test(MessageRouterTest.sendFailsWhenDisconnected "/home/wma/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.sendFailsWhenDisconnected")
add_test(MessageRouterTest.sendFailsWhenPending "/home/wma/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.sendFailsWhenPending")
add_test(MessageRouterTest.sendMessageDoesNotSendAfterDisconnected "/home/wma/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.sendMessageDoesNotSendAfterDisconnected")
add_test(MessageRouterTest.disconnectDisconnectsConnectedTransports "/home/wma/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.disconnectDisconnectsConnectedTransports")
add_test(MessageRouterTest.serverSideDisconnectCreatesANewTransport "/home/wma/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.serverSideDisconnectCreatesANewTransport")
add_test(MessageRouterTest.onReceiveTest "/home/wma/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.onReceiveTest")
add_test(MessageRouterTest.onConnectionStatusChangedTest "/home/wma/sdk-folder/sdk-build/ACL/test/MessageRouterTest" "--gtest_filter=MessageRouterTest.onConnectionStatusChangedTest")
add_test(HTTP2StreamPoolTest.GetStreamSendNullPtrForMoreThanMaxStreams "/home/wma/sdk-folder/sdk-build/ACL/test/HTTP2StreamPoolTest" "--gtest_filter=HTTP2StreamPoolTest.GetStreamSendNullPtrForMoreThanMaxStreams")
add_test(HTTP2StreamPoolTest.initGetFails "/home/wma/sdk-folder/sdk-build/ACL/test/HTTP2StreamPoolTest" "--gtest_filter=HTTP2StreamPoolTest.initGetFails")
add_test(HTTP2StreamPoolTest.initPostFails "/home/wma/sdk-folder/sdk-build/ACL/test/HTTP2StreamPoolTest" "--gtest_filter=HTTP2StreamPoolTest.initPostFails")
add_test(HTTP2StreamPoolTest.PostStreamSendNullPtrForMoreThanMaxStreams "/home/wma/sdk-folder/sdk-build/ACL/test/HTTP2StreamPoolTest" "--gtest_filter=HTTP2StreamPoolTest.PostStreamSendNullPtrForMoreThanMaxStreams")
add_test(HTTP2StreamPoolTest.ReleaseStreamTestSendMoreThanMaxStreams "/home/wma/sdk-folder/sdk-build/ACL/test/HTTP2StreamPoolTest" "--gtest_filter=HTTP2StreamPoolTest.ReleaseStreamTestSendMoreThanMaxStreams")
add_test(HTTP2StreamPoolTest.ReleaseStreamTestAfterNullTest "/home/wma/sdk-folder/sdk-build/ACL/test/HTTP2StreamPoolTest" "--gtest_filter=HTTP2StreamPoolTest.ReleaseStreamTestAfterNullTest")
subdirs(Transport)
